//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.17 at 03:58:49 PM IST 
//


package com.alfaris.ipsh.subscription.soap;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.alfaris.ipsh.subscription.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.alfaris.ipsh.subscription.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddSubscriptionRequest }
     * 
     */
    public AddSubscriptionRequest createAddSubscriptionRequest() {
        return new AddSubscriptionRequest();
    }

    /**
     * Create an instance of {@link SubscriptionDto }
     * 
     */
    public SubscriptionDto createSubscriptionDto() {
        return new SubscriptionDto();
    }

    /**
     * Create an instance of {@link AddSubscriptionResponse }
     * 
     */
    public AddSubscriptionResponse createAddSubscriptionResponse() {
        return new AddSubscriptionResponse();
    }

    /**
     * Create an instance of {@link ServiceResponse }
     * 
     */
    public ServiceResponse createServiceResponse() {
        return new ServiceResponse();
    }

    /**
     * Create an instance of {@link UpdateSubscriptionRequest }
     * 
     */
    public UpdateSubscriptionRequest createUpdateSubscriptionRequest() {
        return new UpdateSubscriptionRequest();
    }

    /**
     * Create an instance of {@link UpdateSubscriptionResponse }
     * 
     */
    public UpdateSubscriptionResponse createUpdateSubscriptionResponse() {
        return new UpdateSubscriptionResponse();
    }

    /**
     * Create an instance of {@link SubscriptionDtoResponce }
     * 
     */
    public SubscriptionDtoResponce createSubscriptionDtoResponce() {
        return new SubscriptionDtoResponce();
    }

    /**
     * Create an instance of {@link JSONObject }
     * 
     */
    public JSONObject createJSONObject() {
        return new JSONObject();
    }

}
